# Site settings
title: Mabel Villalba Jiménez
email: mabelvj@gmail.com
description: "Projects and stuff"
baseurl: ""
url: "https://mabelvj.github.io"
github_username:  mabelvj
linkedin_username:  mabelvj
resume_link: "https://mabelvj.github.io/mabelvj_cv.pdf"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: minima
